// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarfarinManager.Data.Context;

#nullable disable

namespace WarfarinManager.Data.Migrations
{
    [DbContext(typeof(WarfarinDbContext))]
    [Migration("20251227100000_AddMillewinCodeToDoctorData")]
    partial class AddMillewinCodeToDoctorData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
            // This is a partial migration that only adds MillewinCode column to DoctorData
            // The full model snapshot is in WarfarinDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
