// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WarfarinManager.Data.Context;

#nullable disable

namespace WarfarinManager.Data.Migrations
{
    [DbContext(typeof(WarfarinDbContext))]
    [Migration("20251220000000_AddIsManuallyModifiedToINRControl")]
    partial class AddIsManuallyModifiedToINRControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Il modello target è completo nello snapshot
        }
    }
}
