// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WarfarinManager.Data.Context;

#nullable disable

namespace WarfarinManager.Data.Migrations
{
    [DbContext(typeof(WarfarinDbContext))]
    [Migration("20251126051900_AddCHA2DS2VAScFields")]
    partial class AddCHA2DS2VAScFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Il modello target è completo nello snapshot, 
            // quindi questa classe può essere vuota o contenere solo metadati
        }
    }
}
