// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarfarinManager.Data.Context;

#nullable disable

namespace WarfarinManager.Data.Migrations
{
    [DbContext(typeof(WarfarinDbContext))]
    partial class WarfarinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WarfarinManager.Data.Entities.AdverseEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HemorrhagicCategory")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("INRAtEvent")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedINRControlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Management")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThromboticCategory")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeeklyDoseAtEvent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedINRControlId");

                    b.HasIndex("PatientId", "EventDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdverseEvents_Patient_Date");

                    b.ToTable("AdverseEvents", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.BridgeTherapyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BridgeRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EBPMLastDoseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EBPMResumeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EBPMStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocolText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SurgeryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurgeryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThromboembolicRisk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarfarinResumeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarfarinStopDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("BridgeTherapyPlans", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.DailyDose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DoseMg")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("INRControlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("INRControlId");

                    b.ToTable("DailyDoses", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyDoses_DayOfWeek", "[DayOfWeek] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.DoctorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DoctorData", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.DosageSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuidelineUsed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("INRControlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadingDoseAction")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextControlDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PercentageAdjustment")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresEBPM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresVitaminK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("SuggestedWeeklyDose")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklySchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("INRControlId");

                    b.ToTable("DosageSuggestions", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.INRControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ControlDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentWeeklyDose")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("INRValue")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompliant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhaseOfTherapy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "ControlDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_INRControls_Patient_Date");

                    b.ToTable("INRControls", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Indication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicationTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetINRMax")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetINRMin")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndicationTypeCode");

                    b.HasIndex("PatientId", "IsActive")
                        .HasDatabaseName("IX_Indications_Patient_Active");

                    b.ToTable("Indications", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.IndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetINRMax")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetINRMin")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypicalDuration")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_IndicationTypes_Code");

                    b.ToTable("IndicationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tromboembolismo Venoso",
                            Code = "TVP_TREATMENT",
                            Description = "TVP - Trombosi Venosa Profonda (trattamento)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi (primo episodio), indefinito se ricorrente"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tromboembolismo Venoso",
                            Code = "TVP_PROPHYLAXIS",
                            Description = "TVP - Profilassi tromboembolica",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Secondo fattori di rischio"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tromboembolismo Venoso",
                            Code = "PE_TREATMENT",
                            Description = "Embolia Polmonare (trattamento)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi (primo episodio), indefinito se ricorrente"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tromboembolismo Venoso",
                            Code = "TVP_PE_RECURRENT",
                            Description = "TVP/EP ricorrente",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fibrillazione Atriale",
                            Code = "FA_STROKE_PREVENTION",
                            Description = "Fibrillazione Atriale - Prevenzione stroke (CHA₂DS₂-VASc ≥2)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fibrillazione Atriale",
                            Code = "FA_MITRAL_STENOSIS",
                            Description = "FA con stenosi mitralica",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fibrillazione Atriale",
                            Code = "FA_VALVE_PROSTHESIS",
                            Description = "FA con protesi valvolare",
                            TargetINRMax = 3.5m,
                            TargetINRMin = 2.5m,
                            TypicalDuration = "Indefinito"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Protesi Valvolari",
                            Code = "MECHANICAL_MITRAL",
                            Description = "Protesi meccanica mitralica",
                            TargetINRMax = 3.5m,
                            TargetINRMin = 2.5m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Protesi Valvolari",
                            Code = "MECHANICAL_AORTIC",
                            Description = "Protesi meccanica aortica",
                            TargetINRMax = 3.5m,
                            TargetINRMin = 2.5m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Protesi Valvolari",
                            Code = "MECHANICAL_TRICUSPID",
                            Description = "Protesi meccanica tricuspidale",
                            TargetINRMax = 3.5m,
                            TargetINRMin = 2.5m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Protesi Valvolari",
                            Code = "BIOPROSTHESIS_EARLY",
                            Description = "Bioprotesi valvolare (primi 3-6 mesi)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi post-impianto"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Infarto Miocardico",
                            Code = "MI_LV_DYSFUNCTION",
                            Description = "Post-IM con disfunzione ventricolo sinistro (FE <35%)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi, poi rivalutare"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Infarto Miocardico",
                            Code = "MI_ANTERIOR_EXTENSIVE",
                            Description = "Infarto miocardico anteriore esteso",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Infarto Miocardico",
                            Code = "LV_ANEURYSM",
                            Description = "Aneurisma ventricolare sinistro",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Infarto Miocardico",
                            Code = "LV_THROMBUS",
                            Description = "Trombo intraventricolare",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "3-6 mesi (fino a risoluzione trombo)"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Cardiomiopatie",
                            Code = "DILATED_CARDIOMYOPATHY",
                            Description = "Cardiomiopatia dilatativa con FE ridotta (<35%)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito se alto rischio TE"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Sindrome Anticorpi Antifosfolipidi",
                            Code = "APS_ARTERIAL",
                            Description = "Sindrome anticorpi antifosfolipidi (eventi arteriosi)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Sindrome Anticorpi Antifosfolipidi",
                            Code = "APS_VENOUS",
                            Description = "Sindrome anticorpi antifosfolipidi (eventi venosi)",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito (lifelong)"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Sindrome Anticorpi Antifosfolipidi",
                            Code = "APS_RECURRENT",
                            Description = "APS con eventi ricorrenti nonostante INR 2-3",
                            TargetINRMax = 3.5m,
                            TargetINRMin = 2.5m,
                            TypicalDuration = "Indefinito (target più alto)"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Stroke/TIA",
                            Code = "ISCHEMIC_STROKE",
                            Description = "Ictus ischemico cardioembolico",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito se FA o altra cardiopatia emboligena"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Stroke/TIA",
                            Code = "TIA_CARDIOEMBOLIC",
                            Description = "TIA cardioembolico",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito se FA o altra cardiopatia emboligena"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Altre Indicazioni",
                            Code = "PULMONARY_HYPERTENSION",
                            Description = "Ipertensione polmonare primaria",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Indefinito"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Altre Indicazioni",
                            Code = "PERIPHERAL_ARTERIAL_DISEASE",
                            Description = "Arteriopatia periferica severa",
                            TargetINRMax = 3.0m,
                            TargetINRMin = 2.0m,
                            TypicalDuration = "Secondo valutazione vascolare"
                        });
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.InteractionDrug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ACCPManagement")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FCSAManagement")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionEffect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mechanism")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OddsRatio")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecommendedINRCheckDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrugName")
                        .IsUnique()
                        .HasDatabaseName("IX_InteractionDrugs_DrugName");

                    b.ToTable("InteractionDrugs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ACCPManagement = "Monitoraggio stretto INR. Considerare antibiotico alternativo.",
                            Category = "Antibiotic",
                            DrugName = "Cotrimoxazolo (Trimetoprim-Sulfametoxazolo)",
                            FCSAManagement = "Ridurre dose warfarin 25-40% se indispensabile. Controllo INR dopo 3-5 giorni.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP2C9 + inibizione sintesi Vitamina K",
                            OddsRatio = 2.70m,
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 2,
                            ACCPManagement = "Riduzione empirica dose. Monitoraggio stretto.",
                            Category = "Antifungal",
                            DrugName = "Fluconazolo",
                            FCSAManagement = "Ridurre dose warfarin 25-40%. Controllo INR ravvicinato ogni 3-5 giorni.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP2C9",
                            OddsRatio = 4.57m,
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 3,
                            ACCPManagement = "Riduzione significativa dose. Controlli frequenti.",
                            Category = "Antifungal",
                            DrugName = "Voriconazolo",
                            FCSAManagement = "Ridurre dose warfarin 25-40%. Monitoraggio giornaliero INR inizialmente.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP2C9",
                            OddsRatio = 4.57m,
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 4,
                            ACCPManagement = "Riduzione dose empirica 30-50%. Monitoraggio stretto.",
                            Category = "Antibiotic",
                            DrugName = "Metronidazolo",
                            FCSAManagement = "Ridurre dose warfarin 1/3-1/2 se necessario. Controllo INR dopo 3 giorni.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP2C9",
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 5,
                            ACCPManagement = "Controllo INR entro 3-5 giorni dall'inizio.",
                            Category = "Antibiotic",
                            DrugName = "Eritromicina",
                            FCSAManagement = "Monitoraggio INR. Ridurre dose 10-25% se necessario.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP3A4",
                            OddsRatio = 1.86m,
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 6,
                            ACCPManagement = "Controllo INR entro 3-5 giorni.",
                            Category = "Antibiotic",
                            DrugName = "Claritromicina",
                            FCSAManagement = "Monitoraggio INR. Ridurre dose 10-25% se necessario.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP3A4",
                            OddsRatio = 1.86m,
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 7,
                            ACCPManagement = "Controllo INR dopo 5-7 giorni.",
                            Category = "Antibiotic",
                            DrugName = "Ciprofloxacina",
                            FCSAManagement = "Monitoraggio INR. Ridurre dose 10-15% se necessario.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Moderate",
                            Mechanism = "Meccanismo variabile",
                            OddsRatio = 1.69m,
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 8,
                            ACCPManagement = "Controllo INR dopo 5-7 giorni.",
                            Category = "Antibiotic",
                            DrugName = "Levofloxacina",
                            FCSAManagement = "Monitoraggio INR. Ridurre dose 10-15% se necessario.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Moderate",
                            Mechanism = "Meccanismo variabile",
                            OddsRatio = 1.69m,
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 9,
                            ACCPManagement = "Riduzione empirica 25-30%. Controlli settimanali per 6-8 settimane.",
                            Category = "Antiarrhythmic",
                            DrugName = "Amiodarone",
                            FCSAManagement = "Ridurre dose warfarin 20-30% all'inizio. Aumentare 60% alla sospensione.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "High",
                            Mechanism = "Inibizione CYP2C9 + lunga emivita (40-60 giorni)",
                            RecommendedINRCheckDays = 7
                        },
                        new
                        {
                            Id = 10,
                            ACCPManagement = "Controllo INR dopo 7 giorni se terapia prolungata.",
                            Category = "Antibiotic",
                            DrugName = "Azitromicina",
                            FCSAManagement = "Monitoraggio routine. Generalmente non richiede aggiustamento.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Low",
                            Mechanism = "Interazione minore",
                            RecommendedINRCheckDays = 7
                        },
                        new
                        {
                            Id = 11,
                            ACCPManagement = "Aumentare dose 50-100%. Controllo INR ogni 3-5 giorni.",
                            Category = "Antibiotic",
                            DrugName = "Rifampicina",
                            FCSAManagement = "Aumentare dose warfarin fino a 100%. Riduzione rapida in 5-8 giorni dopo stop.",
                            InteractionEffect = "Decreases",
                            InteractionLevel = "High",
                            Mechanism = "Induzione CYP2C9",
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 12,
                            ACCPManagement = "Aumento significativo dose. Controlli frequenti.",
                            Category = "Anticonvulsant",
                            DrugName = "Carbamazepina",
                            FCSAManagement = "Aumentare dose warfarin 50-100%. Monitoraggio stretto.",
                            InteractionEffect = "Decreases",
                            InteractionLevel = "High",
                            Mechanism = "Induzione CYP2C9",
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 13,
                            ACCPManagement = "Aumento significativo dose. Controlli frequenti.",
                            Category = "Anticonvulsant",
                            DrugName = "Fenobarbital",
                            FCSAManagement = "Aumentare dose warfarin 50-100%. Monitoraggio stretto.",
                            InteractionEffect = "Decreases",
                            InteractionLevel = "High",
                            Mechanism = "Induzione CYP2C9",
                            RecommendedINRCheckDays = 5
                        },
                        new
                        {
                            Id = 14,
                            ACCPManagement = "Controlli INR frequenti. Effetto imprevedibile.",
                            Category = "Anticonvulsant",
                            DrugName = "Fenitoina",
                            FCSAManagement = "Effetto bifasico: inizialmente aumenta INR, poi lo riduce. Monitoraggio stretto.",
                            InteractionEffect = "Variable",
                            InteractionLevel = "High",
                            Mechanism = "Induzione CYP2C9 + competizione legame proteine",
                            RecommendedINRCheckDays = 3
                        },
                        new
                        {
                            Id = 15,
                            ACCPManagement = "Sconsigliato uso cronico. Aumenta rischio emorragico.",
                            Category = "NSAID",
                            DrugName = "FANS (Ibuprofene, Diclofenac, Naprossene)",
                            FCSAManagement = "Evitare se possibile. Preferire paracetamolo.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Moderate",
                            Mechanism = "Effetto antiaggregante + gastropatia",
                            RecommendedINRCheckDays = 7
                        },
                        new
                        {
                            Id = 16,
                            ACCPManagement = "Aumenta rischio emorragico. Usare solo se indicato.",
                            Category = "Antiplatelet",
                            DrugName = "Aspirina (>100mg/die)",
                            FCSAManagement = "Valutare rischio/beneficio. Dosi basse. Gastroprotettore.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Moderate",
                            Mechanism = "Effetto antiaggregante sinergico",
                            RecommendedINRCheckDays = 7
                        },
                        new
                        {
                            Id = 17,
                            ACCPManagement = "Nessun aggiustamento routinario necessario.",
                            Category = "PPI",
                            DrugName = "Omeprazolo",
                            FCSAManagement = "Interazione clinicamente poco rilevante. Monitoraggio routine.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Low",
                            Mechanism = "Inibizione minore CYP2C19",
                            RecommendedINRCheckDays = 14
                        },
                        new
                        {
                            Id = 18,
                            ACCPManagement = "Interazione clinicamente non significativa.",
                            Category = "Statin",
                            DrugName = "Simvastatina",
                            FCSAManagement = "Monitoraggio routine. Raramente richiede aggiustamento.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Low",
                            Mechanism = "Interazione minore",
                            RecommendedINRCheckDays = 14
                        },
                        new
                        {
                            Id = 19,
                            ACCPManagement = "Controllo INR dopo 2-4 settimane da modifiche dosaggio.",
                            Category = "Thyroid",
                            DrugName = "Levotiroxina",
                            FCSAManagement = "Monitoraggio INR se cambio dosaggio tiroxina.",
                            InteractionEffect = "Increases",
                            InteractionLevel = "Low",
                            Mechanism = "Aumento catabolismo fattori coagulazione",
                            RecommendedINRCheckDays = 14
                        },
                        new
                        {
                            Id = 20,
                            ACCPManagement = "Limitare consumo. Effetto imprevedibile.",
                            Category = "Other",
                            DrugName = "Alcool (uso cronico/abuso)",
                            FCSAManagement = "Educare paziente: max 1-2 unità/die.",
                            InteractionEffect = "Variable",
                            InteractionLevel = "Moderate",
                            Mechanism = "Uso acuto aumenta INR, uso cronico induce enzimi",
                            RecommendedINRCheckDays = 7
                        });
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "IsActive")
                        .HasDatabaseName("IX_Medications_Patient_Active");

                    b.ToTable("Medications", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCongestiveHeartFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDiabetes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSlowMetabolizer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_FiscalCode");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Patients_Name");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.AdverseEvent", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.INRControl", "LinkedINRControl")
                        .WithMany()
                        .HasForeignKey("LinkedINRControlId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WarfarinManager.Data.Entities.Patient", "Patient")
                        .WithMany("AdverseEvents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedINRControl");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.BridgeTherapyPlan", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.Patient", "Patient")
                        .WithMany("BridgeTherapyPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.DailyDose", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.INRControl", "INRControl")
                        .WithMany("DailyDoses")
                        .HasForeignKey("INRControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("INRControl");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.DosageSuggestion", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.INRControl", "INRControl")
                        .WithMany("DosageSuggestions")
                        .HasForeignKey("INRControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("INRControl");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.INRControl", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.Patient", "Patient")
                        .WithMany("INRControls")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Indication", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.IndicationType", "IndicationType")
                        .WithMany("Indications")
                        .HasForeignKey("IndicationTypeCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarfarinManager.Data.Entities.Patient", "Patient")
                        .WithMany("Indications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndicationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Medication", b =>
                {
                    b.HasOne("WarfarinManager.Data.Entities.Patient", "Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.INRControl", b =>
                {
                    b.Navigation("DailyDoses");

                    b.Navigation("DosageSuggestions");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.IndicationType", b =>
                {
                    b.Navigation("Indications");
                });

            modelBuilder.Entity("WarfarinManager.Data.Entities.Patient", b =>
                {
                    b.Navigation("AdverseEvents");

                    b.Navigation("BridgeTherapyPlans");

                    b.Navigation("INRControls");

                    b.Navigation("Indications");

                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
